MODEL:
  TYPE: deit
  NAME: deit_small_patch14_mask56_224_alpha1
  PATCH_SIZE: 14
  MASK_PATCH_SIZE: 56
  DEIT:
    PATCH_SIZE: 14
    EMBED_DIM: 384
    DEPTHS: 12
    NUM_HEADS: 6
AUG:
  MASKMIX_PROB: 0.5
  MASKMIX_ALPHA: 1.
  PAL_ATTN: True
